
$font = JetBrainsMono Nerd Font

general {
    hide_cursor = true
}

animations {
    enabled = true
    bezier = smooth, 0.25, 0.1, 0.25, 1.0
    animation = fadeIn, 1, 6, smooth
    animation = fadeOut, 1, 6, smooth
    animation = inputFieldDots, 1, 2, smooth
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 6
}

background {
    monitor =
    color = rgba(46,52,64,0.55)
}

# HORA (un toque más arriba)
label {
    monitor =
    # text = $TIME
    text = cmd[update:1000] TZ=localtime date +"%H:%M"
    font_size = 64
    font_family = $font
    color = rgb(236,239,244)

    position = 0, 155
    halign = center
    valign = center
}

# FECHA (más abajo para que haya aire real)
label {
    monitor =
    # text = cmd[update:60000] date +"%d-%m-%Y"
    text = cmd[update:60000] TZ=localtime date +"%d-%m-%Y"
    font_size = 18
    font_family = $font
    color = rgb(136,192,208)

    position = 0, 80
    halign = center
    valign = center
}

label {
    monitor =
    text = Locked
    font_size = 14
    font_family = $font
    color = rgb(229,233,240)

    position = 0, 45
    halign = center
    valign = center
}

# FRASE cada 30s (color distinto, Nord "frost" más suave)
label {
    monitor =
    text = cmd[update:30000] ~/.config/hypr/scripts/lock-quote.sh
    font_size = 16
    font_family = $font
    color = rgba(143,188,187,0.95)

    position = 0, -5
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 260, 50
    position = 0, -95
    halign = center
    valign = center

    outline_thickness = 2
    outer_color = rgb(76,86,106)
    inner_color = rgba(59,66,82,0.85)

    font_color = rgb(236,239,244)
    placeholder_text = password
    fade_on_empty = false

    rounding = 10

    check_color = rgb(163,190,140)
    fail_color = rgb(191,97,106)

    dots_spacing = 0.3
}

