[theme]
theme = "semi-native"

[icons]
icons = "awesome6"

[icons.overrides]
cpu = ""
memory = ""

[separator]
separator = " | "

[[block]]
block = "custom"
command = "whoami"
interval = "once"

[[block]]
block = "cpu"
interval = 2
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "memory"
format = " $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "sound"
driver = "pulseaudio"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "sound"
driver = "pulseaudio"
device_kind = "source"
format = "  { $volume|} {$active_port |}"
[block.active_port_mappings]
"analog-input-rear-mic" = "" # Mapping to an empty string makes `$active_port` absent
"analog-input-front-mic" = "ERR!"

[[block]]
block = "custom"
command = "echo \uf011" # assumes fontawesome icons
interval = "once"
[[block.click]]
button = "left"
cmd = "systemctl `echo -e 'suspend\npoweroff\nreboot\nlogout' | rofi -dmenu`"

[[block]]
block = "battery"
missing_format = ""

[[block]]
block = "time"
interval = 60
format = "  $timestamp.datetime(f:'%R - %a %d/%m')"

[[block]]
block = "custom"
command = "sed 's/  //' <(curl 'https://wttr.in/?format=4' -s)"
interval = 600

[[block]]
block = "pomodoro"
format = " $icon{ $message| } "
#pomodoro_format = " $icon $status_icon{ $completed_pomodoros.tally()|} $time_remaining.duration(hms:true) "
message = "Grind time! 🔥"
break_message = "Break ☕"
notify_cmd = "notify-send 'pomodoro' '{msg}'"
blocking_cmd = false
